### PR TITLE
Pokefactory - generates Pokemon 

### PR DESCRIPTION
**Pull request by AoifeHughes**

### CODE REVIEW

**Comment by phinate** [comment]
Thank you for this @AoifeHughes -- looks like a real promising start for some more in-depth and controllable generation :) 

I'm gonna checkout this branch and play a bit just to make sure I have the hang of this before merging if that's alright!

(+ thank you for tests :D)

**Comment by AoifeHughes** [comment]
As noted during an in-person impromptu meeting, https://github.com/alan-turing-institute/p2lab-pokemon/tree/testing/battles will address some of the minor code annoyances here as well as more tests for valid/invalid teams

**Comment by AoifeHughes** [comment]
Future commit in PR #50  https://github.com/alan-turing-institute/p2lab-pokemon/pull/50/commits/3326f2ccee1b71786af51b5250879078b21ad3c9 removes chances of generating Pokemon which cannot be instantly used for battles

**Comment by AoifeHughes** [comment]
please note the parser stuff changed in more recent PRs

**Pull request merged**
